<a href="https://colab.research.google.com/github/AtharvNiprul74/ANN-Codes/blob/main/ANN%206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

X=np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y=np.array([[0], [1], [1], [0]])

np.random.seed(1)
input_neurons = 2
hidden_neurons = 2
output_neurons = 1

np.random.seed(1)
weights_input_hidden = np.random.rand(input_neurons, hidden_neurons)
weights_hidden_output = np.random.rand(hidden_neurons, output_neurons)

bias_hidden = np.random.rand(1, hidden_neurons)
bias_output = np.random.rand(1, output_neurons)

learning_rate = 0.5
epochs=10000

for i in range(epochs):
    hidden_input = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    final_output = sigmoid(final_input)

    error = Y - final_output

    gd_output = error * sigmoid_derivative(final_output)
    gd_hidden = np.dot(gd_output, weights_hidden_output.T) * sigmoid_derivative(hidden_output)

    weights_hidden_output += np.dot(hidden_output.T, gd_output) * learning_rate
    bias_output += np.sum(gd_output, axis=0, keepdims=True) * learning_rate

    weights_input_hidden += np.dot(X.T, gd_hidden) * learning_rate
    bias_hidden += np.sum(gd_hidden, axis=0, keepdims=True) * learning_rate

    if i % 1000 == 0:
        print(f"Epoch {i}:\nHidden Output:\n{hidden_output}\nFinal Output:\n{final_output}\n")

predictions = sigmoid(np.dot(sigmoid(np.dot(X, weights_input_hidden) + bias_hidden), weights_hidden_output) + bias_output)
print("Predicted output values:")
print(predictions)

Epoch 0:
Hidden Output:
[[0.5464309  0.58554065]
 [0.54645924 0.65653557]
 [0.64640687 0.74381361]
 [0.64643301 0.79709206]]
Final Output:
[[0.62972271]
 [0.63125095]
 [0.63652524]
 [0.63766357]]

Epoch 1000:
Hidden Output:
[[0.5579081  0.39919166]
 [0.58575494 0.93222693]
 [0.7789187  0.94044095]
 [0.79788756 0.9969502 ]]
Final Output:
[[0.27495903]
 [0.62740994]
 [0.56665297]
 [0.59948497]]

Epoch 2000:
Hidden Output:
[[0.00505681 0.09088796]
 [0.13771819 0.96467933]
 [0.1399586  0.96796418]
 [0.83643572 0.99987887]]
Final Output:
[[0.07314159]
 [0.93073686]
 [0.93112166]
 [0.07577059]]

Epoch 3000:
Hidden Output:
[[0.00255616 0.07283786]
 [0.1106966  0.96738949]
 [0.11220544 0.96961392]
 [0.85992131 0.99991702]]
Final Output:
[[0.04618646]
 [0.9583158 ]
 [0.95850025]
 [0.04433005]]

Epoch 4000:
Hidden Output:
[[0.00186498 0.06586844]
 [0.10013911 0.9689941 ]
 [0.10136526 0.97080074]
 [0.87043491 0.99993214]]
Final Output:
[[0.0361755 ]
 [0.9678866 ]
 [0.96801067]
 [0.03380245]]

Epo

In [ ]:
import numpy as np
import pandas as pd

df=pd.read_excel('Student_dataset.xlsx')

# initializing parameters
def init_parameters(layers_dimension):
  print(layers_dimension)
  L=len(layers_dimension)
  parameters={}
  for i in range (1,L):
    parameters['W'+str(i)]=np.ones((layers_dimension[i-1],layers_dimension[i]))*0.1
    parameters['b'+str(i)]=np.zeros((layers_dimension[i],1))

  return parameters

# summation function
def linear_forward(a_prev,W,b):
  Z=np.dot(W.T,a_prev)+b
  return Z

# activation function
def ReLU(Z):
  return np.maximum(0,Z)

# Derivative of ReLU
def dReLU(Z):
    return Z > 0

# sigmoid for output
def sigmoid(Z):
  return 1/(1+np.exp(-Z))


# feedforward propagation
def feed_forward(X,parameters):
  A=X
  caches=[]
  L=len(parameters)//2
  for i in range (1,L):
    A_prev=A
    W=parameters['W'+str(i)]
    b=parameters['b'+str(i)]
    Z=linear_forward(A_prev,W,b)
    A=ReLU(Z)
    cache=(A_prev,W,b,Z)
    caches.append(cache)

  # output layer
  W_out=parameters['W'+str(L)]
  b_out=parameters['b'+str(L)]
  Z_out=linear_forward(A,W_out,b_out)
  cache=(A,W_out,b_out,Z_out)
  caches.append(cache)

  sigmoid_output=sigmoid(Z_out)
  Y_pred=sigmoid_output

  return Y_pred,caches

# Compute gradients and update parameters
def backpropagation(X, Y_true, Y_pred, caches, parameters, learning_rate):
    grads = {}
    L = len(caches)+1   # total number of layers
    m = X.shape[1]       # number of examples

    # loss function binary cross entropy
    eps=1e-15
    loss=-np.mean(Y_true * np.log(Y_pred+eps)+(1-Y_true)*np.log(1-Y_pred+eps))

    # Derivative of loss w.r.t final layer output i.e sigmoid here
    dZ = Y_pred - Y_true
    A_prev, W, b, Z = caches[-1]
    grads["dW" + str(L)] = (1 / m) * np.dot(dZ,A_prev.T)
    grads["db" + str(L)] = (1 / m) * np.sum(dZ, axis=1, keepdims=True)
    dA_prev = np.dot(W, dZ)

    # Hidden layers
    for l in reversed(range(1, L)):
        print(L)
        A_prev, W, b, Z = caches[l - 1]
        dZ = dA_prev * dReLU(Z)
        grads["dW" + str(l)] = (1 / m) * np.dot(dZ,A_prev.T)
        grads["db" + str(l)] = (1 / m) * np.sum(dZ, axis=1, keepdims=True)
        dA_prev = np.dot(W.T,dZ)

    # Update parameters
    for l in range(1, L + 1):
        parameters["W" + str(l)] -= learning_rate * grads["dW" + str(l)]
        parameters["b" + str(l)] -= learning_rate * grads["db" + str(l)]

    return parameters,loss

# input features from excel file
X=df[['CGPA','10th Score','12th Score','IQ']].values.T
y=df[['Placement']].values.T
# print(X)
# init parameters
input_features=X.shape[0]
parameters=init_parameters([input_features,4,3,1])
# forward propagation
for i in range(1000):
    Y_pred, caches = feed_forward(X, parameters)
    parameters,loss = backpropagation(X, y, Y_pred, caches, parameters, learning_rate=0.01)
    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss}")
# final prediction
final_pred=(Y_pred > 0.5).astype(int)
print(f"Final Predictions:{final_pred}")

[4, 4, 3, 1]
4
4


ValueError: shapes (3,4) and (3,10) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:

import numpy as np
import pandas as pd

#cols=['CGPA','10th Score','12th Score','IQ']
#df=pd.read_excel('Student_dataset.xlsx',usecols=cols)

# initializing parameters
def init_parameters(layers_dimension):
  print(layers_dimension)
  L=len(layers_dimension)
  parameters={}
  for i in range (1,L):
    parameters['W'+str(i)]=np.ones((layers_dimension[i],layers_dimension[i-1]))*0.1
    parameters['b'+str(i)]=np.zeros((layers_dimension[i],1))

  return parameters


# feedforward propagation
def feed_forward(X,parameters):
  A=X
  caches=[]
  L=len(parameters)//2
  for i in range (1,L):
    A_prev=A
    W=parameters['W'+str(i)]
    b=parameters['b'+str(i)]
    Z=linear_forward(A_prev,W,b)
    A=ReLU(Z)
    cache=(A_prev,W,b,Z)
    caches.append(cache)

  # output layer
  W_out=parameters['W'+str(L)]
  b_out=parameters['b'+str(L)]
  Z_out=linear_forward(A,W_out,b_out)

  Y_pred=Z_out

  return Y_pred,caches

# Compute gradients and update parameters
def backpropagation(X, Y_true, Y_pred, caches, parameters, learning_rate):
    grads = {}
    L = len(caches) + 1  # total number of layers
    m = X.shape[1]       # number of examples

    # Derivative of loss w.r.t final layer output
    dZ = (Y_pred - Y_true)  # MSE derivative

    # Output layer gradients
    A_prev, W, b, Z = caches[-1]
    grads["dW" + str(L)] = (1/m) * np.dot(dZ,A_prev.T)
    grads["db" + str(L)] = (1/m) * np.sum(dZ, axis=1, keepdims=True)

    dA_prev = np.dot(W.T, dZ)

    # Hidden layers
    for l in reversed(range(1, L-1)):
        A_prev, W, b, Z = caches[l-1]
        dZ = dA_prev * dReLU(Z)
        grads["dW" + str(l+1)] = (1/m) * np.dot(dZ,A_prev.T)
        grads["db" + str(l+1)] = (1/m) * np.sum(dZ, axis=1, keepdims=True)
        dA_prev = np.dot(W, dZ)

    # Update parameters
    for l in range(1, L+1):
        parameters["W" + str(l)] -= learning_rate * grads["dW" + str(l)]
        parameters["b" + str(l)] -= learning_rate * grads["db" + str(l)]

    return parameters

# summation function
def linear_forward(a_prev,W,b):
  Z=np.dot(W,a_prev)+b
  return Z

# activation function
def ReLU(Z):
  return np.maximum(0,Z)

def dReLU(Z):
    return (Z > 0).astype(float)


# input features from excel
data = [
    [8.5, 85, 88, 120, 1],
    [7.2, 78, 74, 110, 0],
    [9.1, 90, 92, 130, 1],
    [6.8, 70, 65, 105, 0],
    [7.5, 75, 78, 115, 0],
    [8.0, 80, 81, 118, 1],
    [7.9, 79, 77, 113, 1],
    [8.3, 83, 85, 125, 1],
    [6.5, 65, 60, 100, 0],
    [9.0, 92, 95, 135, 1]
]
data = np.array(data).T
X=data[:-1, :]  # First 4 rows: features
y = data[-1:, :]
# print(X)
# init parameters
input_features=X.shape[0]
parameters=init_parameters([input_features,4,3,1])
# forward propagation
pred_value,cache=feed_forward(X,parameters)
#print("Predicted Value after Feedforward propagation=",pred_value)
for i in range(1000):
    Y_pred, caches = feed_forward(X, parameters)
    loss = np.mean((Y_pred - y) ** 2)
    parameters = backpropagation(X, y, Y_pred, caches, parameters, learning_rate=0.01)
    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss}")

[4, 4, 3, 1]


ValueError: shapes (4,3) and (1,10) not aligned: 3 (dim 1) != 1 (dim 0)

In [ ]:
import numpy as np
import pandas as pd

# Load dataset
df = pd.read_excel('Student_dataset.xlsx')

# Initialize parameters function
def init_parameters(layers_dimension):
    L = len(layers_dimension)
    parameters = {}
    for i in range(1, L):
        parameters['W' + str(i)] = np.ones((layers_dimension[i-1], layers_dimension[i])) * 0.1
        parameters['b' + str(i)] = np.zeros((layers_dimension[i], 1))
    return parameters

# Summation function
def linear_forward(a_prev, W, b):
    Z = np.dot(W.T, a_prev) + b  # Forward linear computation
    return Z

# ReLU activation function
def ReLU(Z):
    return np.maximum(0, Z)

# Derivative of ReLU
def dReLU(Z):
    return Z > 0  # Gradient of ReLU: derivative = 1 for positive, 0 for negative Z

# Sigmoid for output
def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))

# Feedforward propagation
def feed_forward(X, parameters):
    A = X
    caches = []
    L = len(parameters) // 2  # Number of layers
    for i in range(1, L):
        A_prev = A
        W = parameters['W' + str(i)]
        b = parameters['b' + str(i)]
        Z = linear_forward(A_prev, W, b)
        A = ReLU(Z)
        caches.append((A_prev, W, b, Z))

    # Output layer (sigmoid activation)
    W_out = parameters['W' + str(L)]
    b_out = parameters['b' + str(L)]
    Z_out = linear_forward(A, W_out, b_out)
    caches.append((A, W_out, b_out, Z_out))

    sigmoid_output = sigmoid(Z_out)
    Y_pred = sigmoid_output

    return Y_pred, caches

# Compute gradients and update parameters
def backpropagation(X, Y_true, Y_pred, caches, parameters, learning_rate):
    grads = {}
    L = len(caches) + 1  # Total number of layers
    m = X.shape[1]  # Number of examples

    # Binary cross-entropy loss function
    eps = 1e-15
    loss = -np.mean(Y_true * np.log(Y_pred + eps) + (1 - Y_true) * np.log(1 - Y_pred + eps))

    # Derivative of loss w.r.t final layer output (Sigmoid activation)
    dZ = Y_pred - Y_true
    A_prev, W, b, Z = caches[-1]
    grads["dW" + str(L)] = (1 / m) * np.dot(dZ, A_prev.T)
    grads["db" + str(L)] = (1 / m) * np.sum(dZ, axis=1, keepdims=True)
    dA_prev = np.dot(W.T, dZ)  # Gradient of A_prev

    # Backpropagation for hidden layers
    for l in reversed(range(1, L)):
        A_prev, W, b, Z = caches[l - 1]
        dZ = dA_prev * dReLU(Z)  # Apply ReLU derivative
        grads["dW" + str(l)] = (1 / m) * np.dot(dZ, A_prev.T)
        grads["db" + str(l)] = (1 / m) * np.sum(dZ, axis=1, keepdims=True)
        dA_prev = np.dot(W.T, dZ)  # Backpropagate the gradient

    # Update parameters
    for l in range(1, L + 1):
        parameters["W" + str(l)] -= learning_rate * grads["dW" + str(l)]
        parameters["b" + str(l)] -= learning_rate * grads["db" + str(l)]

    return parameters, loss

# Input features and labels from Excel file
X = df[['CGPA', '10th Score', '12th Score', 'IQ']].values
y = df[['Placement']].values

# Initialize parameters (example: [input features, hidden layer 1, hidden layer 2, output layer])
input_features = X.shape[0]
parameters = init_parameters([input_features, 4, 3, 1])

# Training loop
for i in range(1000):
    Y_pred, caches = feed_forward(X, parameters)  # Feedforward
    parameters, loss = backpropagation(X, y, Y_pred, caches, parameters, learning_rate=0.01)  # Backpropagation

    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss}")

# Final predictions after training
final_pred = (Y_pred > 0.5).astype(int)
print(f"Final Predictions: {final_pred}")


ValueError: shapes (1,3) and (10,4) not aligned: 3 (dim 1) != 10 (dim 0)